version: '3.7'
services:

  express:
    build: ./server
    container_name: express
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    volumes:
      - ./server:/server:ro
      - /server/node_modules
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=example
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - pinakas:/data/db

volumes:
  pinakas: